[project]
name = "video-surveillance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Madhushree Ramachandran", email = "137623310+MadhushreeRamachandran@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ultralytics>=8.2.0",
    "opencv-python>=4.8.0",
    "shapely>=2.0.0",
    "deep-sort-realtime>=1.3.2",
    "numpy>=1.24.0",
    "setuptools<81",
]

[project.scripts]
video-surveillance = "video_surveillance:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
[tool.uv]
package = false
